import pytest
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


@pytest.fixture
def driver(request):
    wd = webdriver.Chrome()
    request.addfinalizer(wd.quit)
    return wd

def test_log_in(driver):
    driver.get('http://localhost/litecart/admin')
    driver.find_element_by_name('username').send_keys('admin')
    driver.find_element_by_name('password').send_keys('admin')
    driver.find_element_by_name('login').submit()
    WebDriverWait(driver, 15).until(EC.title_is('My Store'))

    driver.find_element_by_xpath('//*[@id="app-"]/a/span[@class="name"]').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Template'))
    driver.find_element_by_class_name('Template').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Template'))
    driver.find_element_by_class_name('Logotype').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Logotype'))

    driver.find_element_by_class_name('Catalog').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Catalog'))
    driver.find_element_by_class_name('Product Groups').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Product Groups'))
    driver.find_element_by_class_name('Option Groups').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Option Groups'))
    driver.find_element_by_class_name('Manufacturers').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Manufacturers'))
    driver.find_element_by_class_name('Suppliers').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Suppliers'))
    driver.find_element_by_class_name('Delivery Statuses').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Delivery Statuses'))
    driver.find_element_by_class_name('Sold Out Statuses').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Sold Out Statuses'))
    driver.find_element_by_class_name('Quantity Units').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Quantity Units'))
    driver.find_element_by_class_name('CSV Import/Export').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – CSV Import/Export'))

    driver.find_element_by_class_name('Countries').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Countries'))
    driver.find_element_by_class_name('Currencies').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Currencies'))

    driver.find_element_by_class_name('Customers').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Customers'))
    driver.find_element_by_class_name('CSV Import/Export').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – CSV Import/Export'))
    driver.find_element_by_class_name('Newsletter').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Newsletter'))

    driver.find_element_by_class_name('Geo Zones').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Geo Zones'))

    driver.find_element_by_class_name('Languages').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Languages'))
    driver.find_element_by_class_name('Storage Encoding').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Storage Encoding'))

    driver.find_element_by_class_name('Modules').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Modules'))
    driver.find_element_by_class_name('Shipping Modules').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Shipping Modules'))
    driver.find_element_by_class_name('Payment Modules').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Payment Modules'))
    driver.find_element_by_class_name('Order Modules').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Order Modules'))
    driver.find_element_by_class_name('Order Total Modules').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Order Total Modules'))
    driver.find_element_by_class_name('Job Modules').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Job Modules'))

    driver.find_element_by_class_name('Orders').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Orders'))
    driver.find_element_by_class_name('Order Statuses').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Order Statuses'))

    driver.find_element_by_class_name('Pages').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Pages'))
    driver.find_element_by_class_name('CSV Import/Export').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – CSV Import/Export'))

    driver.find_element_by_class_name('Reports').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Reports'))
    driver.find_element_by_class_name('Monthly Sales').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Monthly Sales'))
    driver.find_element_by_class_name('Most Sold Products').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Most Sold Products'))
    driver.find_element_by_class_name('Most Shopping Customers').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Most Shopping Customers'))

    driver.find_element_by_class_name('Settings').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Settings'))
    driver.find_element_by_class_name('Store Info').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Store Info'))
    driver.find_element_by_class_name('Defaults').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Defaults'))
    driver.find_element_by_class_name('Email').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Email'))
    driver.find_element_by_class_name('Listings').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Listings'))
    driver.find_element_by_class_name('Images').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Images'))
    driver.find_element_by_class_name('Checkout').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Checkout'))
    driver.find_element_by_class_name('Advanced').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Advanced'))
    driver.find_element_by_class_name('Security').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Security'))

    driver.find_element_by_class_name('Slides').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Slides'))

    driver.find_element_by_class_name('Tax').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Tax'))
    driver.find_element_by_class_name('Tax Rates').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Tax Rates'))
    driver.find_element_by_class_name('Tax Classes').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Tax Classes'))

    driver.find_element_by_class_name('Translations').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Translations'))
    driver.find_element_by_class_name('Search Translations').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Search Translations'))
    driver.find_element_by_class_name('Scan Files').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Scan Files'))
    driver.find_element_by_class_name('CSV Import/Export').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – CSV Import/Export'))

    driver.find_element_by_class_name('Users').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – Users'))
    driver.find_element_by_class_name('vQmods').click()
    WebDriverWait(driver, 10).until(EC.title_is('My Store – vQmods'))